openapi: 3.0.1
info:
  title: ' recording/'
  description: Needs description.
  contact:
    name: Zoom Developers
    url: https://zoom.us/developer
    email: developer@zoom.us
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Zoom REST API Documentation
  url: https://zoom.github.io/api
servers:
  - url: https://api.zoom.us/v1
security:
  - api_key: []
  - api_secret: []
tags: []
paths:
  /mc/recording/list:
    post:
      tags:
        - Mc
        - Recording
      description: |+
        Lists all the cloud recordings meetings on a Meeting Connector

      operationId: mcRecordingList
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - host_id
              type: object
              properties:
                host_id:
                  type: string
                  description: Meeting host user ID. Can be any user under this account.
                meeting_number:
                  type: string
                  description: The meeting number.
                from:
                  type: string
                  description: >-
                    The meeting start time after this date, MM/dd/yyyy hh:mm a.
                    For example: 11/05/2014 09:05 pm. Use the host’s time zone,
                    if host has not set time zone, will use GMT.
                to:
                  type: string
                  description: The meeting start time before this date, MM/dd/yyyy hh:mm a.
                page_size:
                  type: string
                  description: >-
                    The amount of records returns within a single API call.
                    Defaults to 30. Max of 300 meetings.
                  default: '30'
                page_number:
                  type: string
                  description: Current page number of returned records. Default to 1.
                  default: '1'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                page_count: 1
                page_number: 1
                page_size: 15
                total_records: 1
                meetings:
                  - uuid: unique_id
                    meeting_number: '123456789'
                    host_id: unique_id
                    account_id: unique_id
                    topic: Meeting Topic
                    start_time: '2014-11-06T04:10:10.000Z'
                    timezone: America/Los_Angeles
                    duration: 999
                    total_size: 4324324324
                    recording_count: 1
                    recording_files:
                      - id: unique_id
                        meeting_id: unique_id
                        recording_start: '2014-11-06T04:14:10.000Z'
                        recording_end: '2014-11-06T04:24:10.000Z'
                        file_type: M4A
                        file_size: 432432
                        play_url: >-
                          https://brand.zoom.us/recording/play/HzMyuI23bqxlJLVJLrww3L9ZuFeZEvYtG0vQ6pHhp6Twr6GPjX4Qks_CJak7jrU2
                        download_url: >-
                          https://brand.zoom.us/recording/download/HzMyuI23bqxlJLVJLrww3L9ZuFeZEvYtG0vQ6pHhp6Twr6GPjX4Qks_CJak7jrU2
      summary: Create Mc Recording List
  /recording/delete:
    post:
      tags:
        - Recording
      description: |+
        Delete recorded meeting either on Zoom cloud or on-premise.

      operationId: recordingDelete
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - meeting_id
              type: object
              properties:
                meeting_id:
                  type: string
                  description: >-
                    The meeting ID. Example: ucc69C82Q5mTNyCRWE29Aw== Or
                    B9C73AF4-2F36-4399-9337-2091584DBD03
                file_id:
                  type: string
                  description: >-
                    The file ID, if given this, will only delete this one file,
                    if not given this, will delete all files of the meeting
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                id: unique_id
                deleted_at: '2012-11-25T12:00:00.000Z'
      summary: Create Recording Delete
  /recording/get:
    post:
      tags:
        - Recording
      description: |+
        Get the recorded meeting on either Zoom cloud or on-prem.

      operationId: recordingGet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - meeting_id
              type: object
              properties:
                meeting_id:
                  type: string
                  description: The meeting ID.
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                uuid: unique_id
                meeting_number: '123456789'
                host_id: unique_id
                account_id: unique_id
                topic: Meeting Topic
                start_time: '2015-04-13T01:06:04.000Z'
                timezone: UTC
                duration: 1
                total_size: 686496
                recording_count: 3
                recording_files:
                  - id: unique_id
                    meeting_id: unique_id
                    recording_start: '2015-04-13T01:06:36.000Z'
                    recording_end: '2015-04-13T01:06:47.000Z'
                    file_type: MP4
                    file_size: 438482
                    play_url: >-
                      https://brand.zoom.us/recording/play/HzMyuI23bqxlJLVJLrww3L9ZuFeZEvYtG0vQ6pHhp6Twr6GPjX4Qks_CJak7jrU2
                    download_url: >-
                      https://brand.zoom.us/recording/download/HzMyuI23bqxlJLVJLrww3L9ZuFeZEvYtG0vQ6pHhp6Twr6GPjX4Qks_CJak7jrU2
      summary: Create Recording Get
  /recording/list:
    post:
      tags:
        - Recording
      description: |+
        List all the cloud recording meetings on Zoom.

      operationId: recordingList
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - host_id
              type: object
              properties:
                host_id:
                  type: string
                  description: Meeting host user ID. Can be any user under this account.
                meeting_number:
                  type: string
                  description: The meeting number.
                from:
                  type: string
                  description: >-
                    The meeting start time after this date, MM/dd/yyyy hh:mm a.
                    For example: 11/05/2014 09:05 pm. Use the host’s time zone,
                    if host has not set time zone, will use GMT.
                to:
                  type: string
                  description: The meeting start time before this date, MM/dd/yyyy hh:mm a.
                page_size:
                  type: string
                  description: >-
                    The amount of records returns within a single API call.
                    Defaults to 30. Max of 300 meetings.
                  default: '30'
                page_number:
                  type: string
                  description: Current page number of returned records. Default to 1.
                  default: '1'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                page_count: 1
                page_number: 1
                page_size: 15
                total_records: 1
                meetings:
                  - uuid: unique_id
                    meeting_number: '123456789'
                    host_id: unique_id
                    account_id: unique_id
                    topic: Meeting Topic
                    start_time: '2014-11-06T04:10:10.000Z'
                    timezone: America/Los_Angeles
                    duration: 999
                    total_size: 4324324324
                    recording_count: 1
                    recording_files:
                      - id: unique_id
                        meeting_id: unique_id
                        recording_start: '2014-11-06T04:14:10.000Z'
                        recording_end: '2014-11-06T04:24:10.000Z'
                        file_type: M4A
                        file_size: 432432
                        status: completed
                        play_url: >-
                          https://brand.zoom.us/recording/play/HzMyuI23bqxlJLVJLrww3L9ZuFeZEvYtG0vQ6pHhp6Twr6GPjX4Qks_CJak7jrU2
                        download_url: >-
                          https://brand.zoom.us/recording/download/HzMyuI23bqxlJLVJLrww3L9ZuFeZEvYtG0vQ6pHhp6Twr6GPjX4Qks_CJak7jrU2
      summary: Create Recording List
components:
  schemas: {}
